// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: thsock.proto

package thprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadTempHumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadTempHumRequest) Reset() {
	*x = ReadTempHumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thsock_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadTempHumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTempHumRequest) ProtoMessage() {}

func (x *ReadTempHumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thsock_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTempHumRequest.ProtoReflect.Descriptor instead.
func (*ReadTempHumRequest) Descriptor() ([]byte, []int) {
	return file_thsock_proto_rawDescGZIP(), []int{0}
}

type ReadTempHumReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Temperature float64 `protobuf:"fixed64,1,opt,name=Temperature,proto3" json:"Temperature,omitempty"`
	Humidity    float64 `protobuf:"fixed64,2,opt,name=Humidity,proto3" json:"Humidity,omitempty"`
}

func (x *ReadTempHumReply) Reset() {
	*x = ReadTempHumReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thsock_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadTempHumReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTempHumReply) ProtoMessage() {}

func (x *ReadTempHumReply) ProtoReflect() protoreflect.Message {
	mi := &file_thsock_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTempHumReply.ProtoReflect.Descriptor instead.
func (*ReadTempHumReply) Descriptor() ([]byte, []int) {
	return file_thsock_proto_rawDescGZIP(), []int{1}
}

func (x *ReadTempHumReply) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ReadTempHumReply) GetHumidity() float64 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

var File_thsock_proto protoreflect.FileDescriptor

var file_thsock_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x68, 0x73, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x74, 0x68, 0x67, 0x72, 0x70, 0x63, 0x22, 0x14, 0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x54, 0x65,
	0x6d, 0x70, 0x48, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x50, 0x0a, 0x10,
	0x52, 0x65, 0x61, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x48, 0x75, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x20, 0x0a, 0x0b, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x48, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x48, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x32, 0x53,
	0x0a, 0x0a, 0x54, 0x65, 0x6d, 0x70, 0x48, 0x75, 0x6d, 0x53, 0x76, 0x63, 0x12, 0x45, 0x0a, 0x0b,
	0x52, 0x65, 0x61, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x48, 0x75, 0x6d, 0x12, 0x1a, 0x2e, 0x74, 0x68,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x48, 0x75, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x74, 0x68, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x52, 0x65, 0x61, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x48, 0x75, 0x6d, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x42, 0x2b, 0x48, 0x03, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x6f, 0x77, 0x2f, 0x74, 0x68, 0x73,
	0x6f, 0x63, 0x6b, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x68, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_thsock_proto_rawDescOnce sync.Once
	file_thsock_proto_rawDescData = file_thsock_proto_rawDesc
)

func file_thsock_proto_rawDescGZIP() []byte {
	file_thsock_proto_rawDescOnce.Do(func() {
		file_thsock_proto_rawDescData = protoimpl.X.CompressGZIP(file_thsock_proto_rawDescData)
	})
	return file_thsock_proto_rawDescData
}

var file_thsock_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_thsock_proto_goTypes = []interface{}{
	(*ReadTempHumRequest)(nil), // 0: thgrpc.ReadTempHumRequest
	(*ReadTempHumReply)(nil),   // 1: thgrpc.ReadTempHumReply
}
var file_thsock_proto_depIdxs = []int32{
	0, // 0: thgrpc.TempHumSvc.ReadTempHum:input_type -> thgrpc.ReadTempHumRequest
	1, // 1: thgrpc.TempHumSvc.ReadTempHum:output_type -> thgrpc.ReadTempHumReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_thsock_proto_init() }
func file_thsock_proto_init() {
	if File_thsock_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_thsock_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadTempHumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thsock_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadTempHumReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_thsock_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_thsock_proto_goTypes,
		DependencyIndexes: file_thsock_proto_depIdxs,
		MessageInfos:      file_thsock_proto_msgTypes,
	}.Build()
	File_thsock_proto = out.File
	file_thsock_proto_rawDesc = nil
	file_thsock_proto_goTypes = nil
	file_thsock_proto_depIdxs = nil
}
